package engine.ihm.net.server;

import com.bulenkov.darcula.DarculaLaf;
import engine.ihm.net.ConsoleHistorique;
import engine.GameContainer;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author lione
 */
public class ServerConsole extends javax.swing.JFrame {

    private GameContainer gc;
    private StyledDocument doc;
    private final ConsoleHistorique historique;

    /**
     * Creates new form Console
     */
    public ServerConsole(GameContainer gc) {
        this.gc = gc;
        try {
            UIManager.setLookAndFeel(new DarculaLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
            System.out.println("asdasd");
        }
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                gc.stopServer();
                gc.endProgram();
            }
        });

        initComponents();
        historique = new ConsoleHistorique();
        historique.executeCommand("start game");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStartStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpConsole = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txfExecutable = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setResizable(false);

        btnStartStop.setText("Start");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        txpConsole.setEditable(false);
        txpConsole.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txpConsole);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Server Console");

        txfExecutable.setBackground(new java.awt.Color(10, 10, 10));
        txfExecutable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfExecutableActionPerformed(evt);
            }
        });
        txfExecutable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfExecutableKeyPressed(evt);
            }
        });

        btnExecute.setText("Execute");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txfExecutable)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnStartStop)
                .addContainerGap(546, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfExecutable)
                        .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        if (!gc.getServer().switchServerState()) {
            switchStartStopButton();
        }
    }//GEN-LAST:event_btnStartStopActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        execute();
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void txfExecutableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfExecutableActionPerformed
        execute();
    }//GEN-LAST:event_txfExecutableActionPerformed

    private void txfExecutableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfExecutableKeyPressed
        String command = null;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                command = historique.getUpCommand();
                break;
            case KeyEvent.VK_DOWN:
                command = historique.getDownCommand();
                break;
        }
        if (command != null) {
            txfExecutable.setText(command);
        }
    }//GEN-LAST:event_txfExecutableKeyPressed

    private void execute() {
        gc.getServer().executeCommand(txfExecutable.getText(), -1);
        historique.executeCommand(txfExecutable.getText());
        txfExecutable.setText("");
    }

    /**
     * Change the title and the Start/Stop button depending on the current state
     * of the server
     */
    public void switchStartStopButton() {
        btnStartStop.setText(btnStartStop.getText().equals("Start") ? "Stop" : "Start");
    }

    /**
     * Appends text in the console, handles colors : If begins with '#', then
     * the following char defines the color. Exemple : #rHey ! Will be written
     * red -r Red -g Green -b Blue -y Yellow -o Orange -- White -w White
     *
     * @param txt The text to write
     */
    public synchronized void writeConsole(String txt) {
        try {
            doc = txpConsole.getStyledDocument();
            Style style = txpConsole.addStyle("I'm a Style", null);
            String[] words = txt.split(" ");
            Color lastColor = Color.white;
            for (String w : words) {
                if (w.startsWith("#")) {
                    //color handling
                    switch (w.charAt(1)) {
                        case 'r':
                            StyleConstants.setForeground(style, Color.red);
                            lastColor = Color.red;
                            break;
                        case 'g':
                            StyleConstants.setForeground(style, Color.green);
                            lastColor = Color.green;
                            break;
                        case 'b':
                            StyleConstants.setForeground(style, Color.blue);
                            lastColor = Color.blue;
                            break;
                        case 'y':
                            StyleConstants.setForeground(style, Color.yellow);
                            lastColor = Color.yellow;
                            break;
                        case 'c':
                            StyleConstants.setForeground(style, Color.cyan);
                            lastColor = Color.cyan;
                            break;
                        case 'o':
                            StyleConstants.setForeground(style, Color.orange);
                            lastColor = Color.orange;
                            break;
                        case 'm':
                            StyleConstants.setForeground(style, Color.magenta);
                            lastColor = Color.magenta;
                            break;
                        case 'p':
                            StyleConstants.setForeground(style, Color.pink);
                            lastColor = Color.pink;
                            break;
                        default:
                        case 'w':
                        case '-':
                            StyleConstants.setForeground(style, Color.white);
                            lastColor = Color.white;
                            break;
                    }
                    doc.insertString(doc.getLength(), w.substring(2), style);
                } else {
                    StyleConstants.setForeground(style, lastColor);
                    doc.insertString(doc.getLength(), w, style);
                }
                doc.insertString(doc.getLength(), " ", style);

            }
            doc.insertString(doc.getLength(), "\n", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(ServerConsole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnStartStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txfExecutable;
    private javax.swing.JTextPane txpConsole;
    // End of variables declaration//GEN-END:variables

}
